### ISSUE TITLE
After "Modularizing" is introduced, index.js -> const game is undefined in console

### ISSUE THREAD

**Issue by BrettMCoding** [mikewesthad/phaser-3-tilemap-blog-posts#2]
First off, thanks for the tutorials! I'm learning a lot. After Post-2 Part 01, we step into 02-modules-demo. Afterwards, the console in google chrome sees game (From index.js const game = new Phaser.Game(config)) as undefined.

This might be just a "me" issue with something I do not understand. If that's the case, could you tell me how I can access my game objects / variables from the console so I can play with things on the go?

**Comment by mikewesthad** [comment]
Hi - glad you've found them helpful.

One of the big picture motivations for modules in programming is that they are self-contained. A variable or function inside of a file called enemy.js can't be touched by code running inside of world.js, unless you `export` it from enemy.js and `import` it inside of world.js. (I'd recommend checking out [this chapter](https://eloquentjavascript.net/10_modules.html) for more on modules.)

From how I'm picturing you are using the console - the same self-contained concept applies there. If you are opening the console while the game is running and typing in the name of a local variable from a module, it won't work. The console is only going to have access to the global scope that way. I'd recommend checking out the [debugger](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/debugger) command & the Chrome [tutorial](https://developers.google.com/web/tools/chrome-devtools/javascript/) on using the debugger. If you've got dev tools open when the browser hits a line with `debugger`, it will pause the code execution and let you play with any variables in the current scope.

Let's say you want to modify variables (like gravity or the player's jump force) on-the-fly while running the game. Some options:

- Though you don't really want to rely on doing this from a code architecture standpoint, you can still pop variables onto the global `window` object, which every module & the console can access. E.g. `window.player = player` would make an existing player instance accessible to the console.
- Create an HTML debug menu with sliders, checkboxes and the like to control settings.
- Create hotkeys, e.g. bind a function that increases the gravity by a small amount to `g`. You could also bind a function that runs `debugger` to a key. Then you'd have access to anything in the scope.

**Comment by BrettMCoding** [comment]
That's so nice of you to write out for me man. Thank you. Have a nice day.

**Comment by mikewesthad** [comment]
No problem - good luck with it!
